title: Tutorial GitHub Pages
author: Adrian Ramos
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Esto es un tutorial para aprender a utilizar de manera correcta
  GitHub Pages

theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
